Create service for face recognition
SeymourCray/backend-face pull request #4
Opened 2022-11-01 09:33 UTC by molel

2022-11-01 10:25 UTC, erlnby requested changes

2022-11-01 10:25 UTC, erlnby commented on .github/workflows/ci.yml
> +        name: Lint
Повторяющийся шаг из lint

2022-11-01 10:25 UTC, erlnby commented on .github/workflows/ci.yml
> +    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
Посмотреть, как можно проще описать это правило

2022-11-01 10:25 UTC, erlnby commented on .github/workflows/ci.yml
> +        id: date
Посмотреть как можно ещё опсить timestamp

2022-11-01 10:25 UTC, erlnby commented on internal/controller/user.go
> +	if err := json.NewDecoder(request.Body).Decode(&userGet); err != nil || len(userGet.Encoding) != 256 {
Вынести длину encoding в константу

2022-11-01 10:25 UTC, erlnby commented on docker-compose.yml
> +      - "27017:27017"
Убрать пробрасывание портов наружу

2022-11-01 10:25 UTC, erlnby commented on docker-compose.yml
> +      - "8080:80"
Добавить динамическое назначение порта

2022-11-01 10:25 UTC, erlnby commented on production.yml
> +version: '3.8'
Переименовать в docker-compose.yml

2022-11-01 10:25 UTC, erlnby commented on docker-compose.yml
> +version: '3.8'
Переименовать в docker-compose.dev.yml

2022-11-02 08:11 UTC, nktrnv commented on .github/workflows/ci.yml
> +        name: Lint
+

2022-11-02 08:11 UTC, nktrnv commented on .github/workflows/ci.yml
> +    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
Done

2022-11-02 09:08 UTC, nktrnv commented on .github/workflows/ci.yml
> +        id: date
Done

2022-11-03 15:45 UTC, molel commented on docker-compose.yml
> +version: '3.8'
Done

2022-11-03 15:45 UTC, molel commented on production.yml
> +version: '3.8'
Done

2022-11-03 15:45 UTC, molel commented on docker-compose.yml
> +      - "8080:80"
Done

2022-11-03 17:16 UTC, molel commented on docker-compose.yml
> +      - "27017:27017"
Done

2022-11-05 14:17 UTC, SeymourCray commented on internal/controller/user.go
> +	if err := json.NewDecoder(request.Body).Decode(&userGet); err != nil || len(userGet.Encoding) != 256 {
Done

2022-11-09 15:58 UTC, erlnby commented on internal/controller/user.go
> +	if err := json.NewDecoder(request.Body).Decode(&userGet); err != nil || len(userGet.Encoding) != 256 {
Плохое название константы

2022-11-09 16:21 UTC, erlnby approved these changes

2022-11-09 16:22 UTC, merged